"""Initial migration based on existing database

Revision ID: 292653104d68
Revises: 
Create Date: 2024-11-26 14:57:37.716438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292653104d68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Adicionar a coluna 'realizado' com valor padrão False
    with op.batch_alter_table('contabilidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realizado', sa.Boolean(), nullable=False, server_default=sa.false()))

    # Alterar coluna (se necessário, remover default)
    with op.batch_alter_table('contabilidade', schema=None) as batch_op:
        batch_op.alter_column('realizado', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contabilidade', schema=None) as batch_op:
        batch_op.drop_column('realizado')

    # ### end Alembic commands ###
