"""Add evento_titulo column to Contabilidade

Revision ID: 4175bc625427
Revises: 292653104d68
Create Date: 2024-11-26 18:30:30.424474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4175bc625427'
down_revision = '292653104d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contabilidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evento_titulo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contabilidade', schema=None) as batch_op:
        batch_op.drop_column('evento_titulo')

    # ### end Alembic commands ###
