"""Add data_realizacao to Contabilidade

Revision ID: 66d0a12a2b60
Revises: 4175bc625427
Create Date: 2024-12-03 09:26:39.562950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d0a12a2b60'
down_revision = '4175bc625427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contabilidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_realizacao', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contabilidade', schema=None) as batch_op:
        batch_op.drop_column('data_realizacao')

    # ### end Alembic commands ###
