"""Add data_evento_original to Contabilidade

Revision ID: a49bed1d3de3
Revises: 66d0a12a2b60
Create Date: 2024-12-17 09:20:36.393601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49bed1d3de3'
down_revision = '66d0a12a2b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contabilidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_evento_original', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contabilidade', schema=None) as batch_op:
        batch_op.drop_column('data_evento_original')

    # ### end Alembic commands ###
